### ISSUE TITLE
Change Ensembl API Version

### ISSUE THREAD

**Issue by cyriltata** [bahlolab/PLASTER#16]
Where can one change the ensembl api version? I get this error because my DB is 106. Tried on this line https://github.com/bahlolab/PLASTER/blob/master/test/typing.config#L7 with no success

```
Command error:
  Possible precedence issue with control flow operator at /opt/conda/envs/PLASTER_22.05.01/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 805.

  -------------------- WARNING ----------------------
  MSG: homo_sapiens is not a valid species name (check DB and API version)
  FILE: Bio/EnsEMBL/Registry.pm LINE: 1334
  CALLED BY: Bio/EnsEMBL/Registry.pm  LINE: 1109
  Date (localtime)    = Sat May 28 16:27:45 2022
  Ensembl API version = 104
  ---------------------------------------------------
```

**Comment by jemunro** [comment]
It's probably because the version of ensemble-vep installed in docker container is 104, and is not compatible with future database versions. The easiest solution would be for you to download vep cache GRCh38 version 104 from http://ftp.ensembl.org/pub/release-104/variation/indexed_vep_cache/homo_sapiens_vep_104_GRCh38.tar.gz, see https://ensembl.org/info/docs/tools/vep/script/vep_cache.html

**Comment by cyriltata** [comment]
@jemunro downgraded the database and it worked
